### ISSUE TITLE
Please verify the script

### ISSUE THREAD

**Issue by Vyrastas** [Vyrastas/bbcode_guide_template#10]
I'm going to push the update script today... I've added the note about slowness.  @slammajamma28  can you double-check that it works fine for you as it now before I push it?

**Comment by slammajamma28** [comment]
Just pulled down the master and deployed it.

I see the new note and have verified the lists are populating as expected.

**Comment by Vyrastas** [comment]
Sweet, thank you sir.  I've pushed the script to the production site.
