### ISSUE TITLE
Trophy lists not showing

### ISSUE THREAD

**Issue by slammajamma28** [Vyrastas/bbcode_guide_template#11]
When trying to click into a game to get the actual BBCode, nothing loads. Through browser debugging, I can see the request come back with the correct information, but the frame doesn't seem to be loading with the data. You can right-click the game and the BBCode will load into a new tab just fine.

I've tried both XBA and PST with a variety of letters and games. I've tried both Firefox and Chrome.

I noticed that toward the tail end of a Letter loading, I could see something that looked like a loading icon... I saw in debugging that there was indeed a gif for it. But I don't see reference to this in the code, so I was wondering if perhaps this was something side-loaded that might be affecting it?

**Comment by Vyrastas** [comment]
Sorry about that, yes I was testing out a loading icon and it wasn't working correctly on my web host (of course it works perfectly locally)... I left the code there as I could've sworn the trophy list code was generating fine, but perhaps not.  I've reverted the page back it's working again.
