### ISSUE TITLE
Template for Halo: The Master Chief Collecton Xbox One not showing full achievement list

### ISSUE THREAD

**Issue by bLaKgRaVy** [Vyrastas/bbcode_guide_template#3]
Hello,

We've encountered an issue with the Halo: Master Chief Collection template on xboxachievements.com.

They just released 100 more achievements for 1000 gamerscore for the Halo: Reach DLC, making the list at 700 achievements for 7000 gamerscore.

https://www.xboxachievements.com/game/halo-the-master-chief-collection/achievements/

The template is only showing 534 achievements for 5205 gamerscore. 

http://www.vyrastas.com/ps3t_guide_template.php?site=x360a&game=halo-the-master-chief-collection

Before Reach was added to the game, it was at 600 achievements for 6000 gamerscore. So 66 achievements for 795 gamerscore are missing from the template _before_ adding Halo: Reach.

We're positive that the template was correct at one time (600/6000) because a guide team member wrote the guide for 600/6000 and if there was an issue before now he would have mentioned it. He just recently accessed the template to start writing Reach when he noticed this issue.

If you could look into this it would be greatly appreciated.

**Comment by Vyrastas** [comment]
Thanks for letting me know, I'll take a look today... 

(PS that's a lot of achievements)

**Comment by Vyrastas** [comment]
@bLaKgRaVy do you know offhand if there are other games with this many achievements?  I.e. anything else more than 534?

**Comment by bLaKgRaVy** [comment]
Sorry for not getting back to you sooner. I did some site research and the next closest game as far as achievements are concerned is the Halo Master Chief Collection Chinese release with 479 achievements.

Here's the breakdown:
Games with 100-199 achievements - 33
Games with 200-299 achievements - 3 (Rare Replay [200], Elite: Dangerous [221], Smite [276])
Games with 300-399 achievements - none
Games with 400-499 achievements - 2 (Killer Instinct [464], Halo MCC Chinese [479])
Games with more than 500 achievements - 1 (Halo MCC [700])

I checked both Killer Instinct and Halo MCC CN and their templates are correct.

**Comment by Vyrastas** [comment]
No worries, it's fixed now, please verify.  Just had to increase the maximum file size allowed for the HTML parser... the source for that achievements page went over the limit so it was truncated.

Fixed with commit 3906c1de91e954101e9cdf7b252b405a4864b5dd

**Comment by bLaKgRaVy** [comment]
Awesome! Thanks for all your help, both now and always!

**Comment by Vyrastas** [comment]
No problem 😄
