### ISSUE TITLE
Scraping stops at page 9

### ISSUE THREAD

**Issue by slammajamma28** [Vyrastas/bbcode_guide_template#4]
Someone asked me about Tropico 6 not being on the template page earlier. I poked around and it appears that each list is stopping at page 9.

Click S shows the last PS4 game as "Super Hyperactive Ninja (NA)" which is the final game on page 9 of the PS4 S games (https://www.playstationtrophies.org/browsegames/ps4/s/9).

Similar for T, Tropico 5 is the last game listed on your site which is the last game listed on page 9 of the PS4 T games (https://www.playstationtrophies.org/browsegames/ps4/t/9).

Seems its a simple case of the catalog growing large!

https://github.com/Vyrastas/bbcode_guide_template/blob/master/ps3t_game_list.php
Line 99: 
`for ($j = 1; $j <= 9; $j++) `

It just needs to be increased from 9. For reference, here are the number of pages available for each:

\# - 1
A - 10
B - 5
C - 5
D - 8
E - 3
F - 4
G - 4
H - 3
I - 2
J - 2
K - 2
L - 4
M - 6
N - 3
O - 2
P - 5
Q - 1
R - 5
S - 11
T - 10
U - 1
V - 2
W - 4
X - 1
Y - 1
Z - 1

**Comment by Vyrastas** [comment]
Hey @slammajamma28, yeah that's all it is... 9 was a lot back when I made the script, it was easier to hard-code than try to do it dynamically.  I'll bump it up to 20 when I get home and let you know.

**Comment by slammajamma28** [comment]
20 should cover us for a few more years! :)

**Comment by slammajamma28** [comment]
Well... I was bored this morning and tried my hand at implementing dynamic page numbering.

I'm going to make a pull request so you can take a look at it if you'd like. I'm sure I've mentioned this before but I have minimal exposure to PHP. So if it looks like garbage, feel free to just ignore it lol

**Comment by Vyrastas** [comment]
Oh great, thanks I'll take a look. 👍  I'll need to test that it works for so won't have feedback until tonight.

Speaking of that, I didn't get the template updated last night, sorry.  I'll get it tonight for sure.  In the meantime if someone needs a template for a game that doesn't appear in the game list, they can create it directly as explained here: https://github.com/Vyrastas/bbcode_guide_template#how-it-works

**Comment by slammajamma28** [comment]
No worries, the impact is relatively little and I know you'll get around to it!

I was able to pull Tropico 6 for the other person... I remembered you giving me that "hack" before 👍

**Comment by Vyrastas** [comment]
Should be fixed now!
