### ISSUE TITLE
Pagination Update

### ISSUE THREAD

**Issue by slammajamma28** [Vyrastas/bbcode_guide_template#6]
Just getting this over to you ASAP... hopefully you haven't pushed the change out to the site yet...

I'm sure you're thinking _Slamma, didn't we just work on updating the site so that it would handle dynamically updating number of pages to scrape based on pagination?_ Yes, Vy. Yes we did. But... believe it or not, the pagination as been updated on PST! Someone posted about how XBA and PST were different and bah humbug RX went and updated pagination on PST so it matches XBA.

OF COURSE!!! 

I just launched the Guide Template and it is still working so I'm guessing the change we worked on isn't live yet. But we'll need to get rid of the XBA/PST difference when fetching the max page number. I'm loading up my local version and will post another pull request to fix it.

**Comment by slammajamma28** [comment]
Easy change, [pull request created](https://github.com/Vyrastas/bbcode_guide_template/pull/7)!

**Comment by Vyrastas** [comment]
LOL why am I not surprised.  I didn't push the code because I wanted to add the note about slower load times.  I'll do it today for realz.
