### ISSUE TITLE
Things are blank

### ISSUE THREAD

**Issue by slammajamma28** [Vyrastas/bbcode_guide_template#8]
PST was having issues a little while ago so I thought it was related, but the site is back up now. 

Nothing is returning on the template for clicking a letter on either site... oh dear.

**Comment by slammajamma28** [comment]
RX thinks he may have banned the IP from your site... so that will probably fix it when he restores your IP... was worried again the update was pushed. I don’t think I could handle being a site admin to any critical website this is stressful lol

**Comment by slammajamma28** [comment]
Yep fixed. Woo sorry for the false alarm and concern

**Comment by Vyrastas** [comment]
PST is a critical website?  🤔   Or did you mean the Guide Template? 😎

**Comment by slammajamma28** [comment]
OF COURSE I'm talking about the Guide Template!
